name: Sync GitHub to Gitee

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync GitHub to Gitee
        run: |
          git clone --mirror https://github.com/${{ github.repository }}.git repo.git

          cd repo.git

          git remote add gitee https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_USERNAME }}/${{ github.event.repository.name }}.git

          git for-each-ref --format='delete %(refname)' refs/pull | git update-ref --stdin || true

          git push gitee --mirror