name: Sync GitHub to Gitee

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror to Gitee
        env:
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git clone --mirror https://github.com/${{ github.repository }}.git repo.git

          cd repo.git

          git push --mirror https://${GITEE_USERNAME}:${GITEE_TOKEN}@gitee.com/${GITEE_USERNAME}/${{ github.event.repository.name }}.git